FROM php:7.0-apache
MAINTAINER Ariel Bottero <ab@abcontenidos.com>

# ENV variables
ENV PHP_TIMEZONE America/Argentina/Buenos_Aires
ENV APACHE_DOC_ROOT /var/www/html

# apt-get update
RUN apt-get update

# tools
RUN apt-get install -y \
	apt-utils \
	nano \
	git

# Install GD
RUN apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install gd

# Install Zip
RUN docker-php-ext-install zip

# Install MCrypt
RUN apt-get install -y libmcrypt-dev \
    && docker-php-ext-install mcrypt

# Install Mysql
RUN docker-php-ext-install mysqli

# Install SOAP
RUN apt-get install -y libxml2-dev \
    && docker-php-ext-install soap

# Additional PHP ini configuration
COPY ./php.ini /usr/local/etc/php/conf.d/

# Enable Apache mod_rewrite
RUN a2enmod rewrite

# Restart Apache
RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf
RUN service apache2 restart